name: release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build

    - name: dotnet pack
      run: dotnet pack -c Release /p:Version=${GITHUB_REF_NAME#v} -o drop/nuget

    - name: dotnet publish
      run: |
        dotnet publish src/docfx -f net8.0 -c Release /p:Version=${GITHUB_REF_NAME#v} --self-contained -r win-x64 -o drop/publish/win-x64
        dotnet publish src/docfx -f net8.0 -c Release /p:Version=${GITHUB_REF_NAME#v} --self-contained -r linux-x64 -o drop/publish/linux-x64
        dotnet publish src/docfx -f net8.0 -c Release /p:Version=${GITHUB_REF_NAME#v} --self-contained -r osx-x64 -o drop/publish/osx-x64
        mkdir -p drop/bin

    - run: zip -r ../../bin/docfx-win-x64-${GITHUB_REF_NAME}.zip .
      working-directory: drop/publish/win-x64
    - run: zip -r ../../bin/docfx-linux-x64-${GITHUB_REF_NAME}.zip .
      working-directory: drop/publish/linux-x64
    - run: zip -r ../../bin/docfx-osx-x64-${GITHUB_REF_NAME}.zip .
      working-directory: drop/publish/osx-x64

    - uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: drop/nuget

    - uses: actions/upload-artifact@v4
      with:
        name: bin
        path: drop/bin

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - uses: actions/download-artifact@v4
      with:
        name: nuget
        path: drop/nuget

    - uses: actions/download-artifact@v4
      with:
        name: bin
        path: drop/bin

    - name: Upload GitHub release
      run: |
        gh release upload --repo dotnet/docfx ${GITHUB_REF_NAME} drop/bin/docfx-win-x64-${GITHUB_REF_NAME}.zip
        gh release upload --repo dotnet/docfx ${GITHUB_REF_NAME} drop/bin/docfx-linux-x64-${GITHUB_REF_NAME}.zip
        gh release upload --repo dotnet/docfx ${GITHUB_REF_NAME} drop/bin/docfx-osx-x64-${GITHUB_REF_NAME}.zip
      env:
        GH_TOKEN: ${{ github.token }}
